### PR TITLE
bugfix: close socket on error

### PR DESCRIPTION
**Pull request by thiagotognoli**
Bugfix: Close the socket when an error occurs
Bugfix: Added ts typings to server

### CODE REVIEW

**Comment by luk3skyw4lker** [comment]
I'll be reviewing the code today and if it works I'll be merging.

**Comment by tbn-mm** [comment]
Any update? This also adds **important** TS declarations!

**Review by luk3skyw4lker — APPROVED** [review]

**Comment by luk3skyw4lker** [comment]
LGTM! I'll publish the updated version on NPM right now

**Comment by luk3skyw4lker** [comment]
Version published with the updates! Thanks for the contribution and sorry to take so long to review it!

**Pull request merged**
